/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppMatchesRouteImport } from './routes/_app/matches'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppUniversesRouteImport } from './routes/_app/universes'
import { Route as AppChatChatIdRouteImport } from './routes/_app/chat.$chatId'
import { Route as AppPeopleUserIdRouteImport } from './routes/_app/people.$userId'
import { Route as AppUniversesUniverseIdRouteImport } from './routes/_app/universes.$universeId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppUniversesRoute = AppUniversesRouteImport.update({
  id: '/universes',
  path: '/universes',
  getParentRoute: () => AppRoute,
} as any)
const AppChatChatIdRoute = AppChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleUserIdRoute = AppPeopleUserIdRouteImport.update({
  id: '/people/$userId',
  path: '/people/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppUniversesUniverseIdRoute = AppUniversesUniverseIdRouteImport.update({
  id: '/$universeId',
  path: '/$universeId',
  getParentRoute: () => AppUniversesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/discover': typeof AppDiscoverRoute
  '/matches': typeof AppMatchesRoute
  '/me': typeof AppMeRoute
  '/universes': typeof AppUniversesRouteWithChildren
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/people/$userId': typeof AppPeopleUserIdRoute
  '/universes/$universeId': typeof AppUniversesUniverseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/discover': typeof AppDiscoverRoute
  '/matches': typeof AppMatchesRoute
  '/me': typeof AppMeRoute
  '/universes': typeof AppUniversesRouteWithChildren
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/people/$userId': typeof AppPeopleUserIdRoute
  '/universes/$universeId': typeof AppUniversesUniverseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/matches': typeof AppMatchesRoute
  '/_app/me': typeof AppMeRoute
  '/_app/universes': typeof AppUniversesRouteWithChildren
  '/_app/chat/$chatId': typeof AppChatChatIdRoute
  '/_app/people/$userId': typeof AppPeopleUserIdRoute
  '/_app/universes/$universeId': typeof AppUniversesUniverseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboard'
    | '/discover'
    | '/matches'
    | '/me'
    | '/universes'
    | '/chat/$chatId'
    | '/people/$userId'
    | '/universes/$universeId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboard'
    | '/discover'
    | '/matches'
    | '/me'
    | '/universes'
    | '/chat/$chatId'
    | '/people/$userId'
    | '/universes/$universeId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboard'
    | '/_app/discover'
    | '/_app/matches'
    | '/_app/me'
    | '/_app/universes'
    | '/_app/chat/$chatId'
    | '/_app/people/$userId'
    | '/_app/universes/$universeId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matches': {
      id: '/_app/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/universes': {
      id: '/_app/universes'
      path: '/universes'
      fullPath: '/universes'
      preLoaderRoute: typeof AppUniversesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$chatId': {
      id: '/_app/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AppChatChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$userId': {
      id: '/_app/people/$userId'
      path: '/people/$userId'
      fullPath: '/people/$userId'
      preLoaderRoute: typeof AppPeopleUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/universes/$universeId': {
      id: '/_app/universes/$universeId'
      path: '/$universeId'
      fullPath: '/universes/$universeId'
      preLoaderRoute: typeof AppUniversesUniverseIdRouteImport
      parentRoute: typeof AppUniversesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppUniversesRouteChildren {
  AppUniversesUniverseIdRoute: typeof AppUniversesUniverseIdRoute
}

const AppUniversesRouteChildren: AppUniversesRouteChildren = {
  AppUniversesUniverseIdRoute: AppUniversesUniverseIdRoute,
}

const AppUniversesRouteWithChildren = AppUniversesRoute._addFileChildren(
  AppUniversesRouteChildren,
)

interface AppRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppMeRoute: typeof AppMeRoute
  AppUniversesRoute: typeof AppUniversesRouteWithChildren
  AppChatChatIdRoute: typeof AppChatChatIdRoute
  AppPeopleUserIdRoute: typeof AppPeopleUserIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppMeRoute: AppMeRoute,
  AppUniversesRoute: AppUniversesRouteWithChildren,
  AppChatChatIdRoute: AppChatChatIdRoute,
  AppPeopleUserIdRoute: AppPeopleUserIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
